### ISSUE TITLE
Docs.rs documentation broken

### ISSUE THREAD

**Issue by roblabla** [thisKai/rust-windows-dll#3]
Hey, thanks for the new release! The documentation on docs.rs is broken though, it appears to be building for the linux target :scream: 

I believe the problem is that despite having set the default targets, all the other targets are still being built, and maybe it fails on the first build failure?

I looked at how winapi does it, and I believe this is the correct way to make it work:

```toml
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]
```
